def load_dataset_model(dataset_description_identifier)
  dataset_description = DatasetDescription.find_by_identifier(dataset_description_identifier)
  dataset_description.dataset.dataset_record_class
end