# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
defaults: &defaults
  adapter: mysql2
  timeout: 5000
  encoding: utf8
  pool: 5
  username: <%= ENV['DATANEST_MYSQL_USER'] %>
  password: <%= ENV['DATANEST_MYSQL_PASSWORD'] %>
  host: <%= ENV['DATANEST_MYSQL_HOST'] %>
  port: 3306
  socket: <%= ENV['DATANEST_MYSQL_SOCKET'] %>

development:
  <<: *defaults
  database: datanest_app_development

development_data:
  <<: *defaults
  database: datanest_data_development

development_staging:
  <<: *defaults
  database: datanest_staging_development

staging:
  <<: *defaults
  database: datanest_app_staging

staging_data:
  <<: *defaults
  database: datanest_data_staging

staging_staging:
  <<: *defaults
  database: datanest_staging_staging

production:
  <<: *defaults
  database: datanest_app_production

production_data:
  <<: *defaults
  database: datanest_data_production

production_staging:
  <<: *defaults
  database: datanest_staging_production

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  <<: *defaults
  database: datanest_app_test

test_data:
  <<: *defaults
  database: datanest_data_test

test_staging:
  <<: *defaults
  database: datanest_staging_test

cucumber:
  <<: *test
